config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  root 'karts#index'
  resources :karts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kart.rb
class Kart < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/karts_controller.rb
class KartsController < ApplicationController
  before_action :set_kart, only: %i[ show edit update destroy ]

  # GET /karts or /karts.json
  def index
    @karts = Kart.all
  end

  # GET /karts/1 or /karts/1.json
  def show
  end

  # GET /karts/new
  def new
    @kart = Kart.new
  end

  # GET /karts/1/edit
  def edit
  end

  # POST /karts or /karts.json
  def create
    @kart = Kart.new(kart_params)

    respond_to do |format|
      if @kart.save
        format.html { redirect_to kart_url(@kart), notice: "Kart was successfully created." }
        format.json { render :show, status: :created, location: @kart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /karts/1 or /karts/1.json
  def update
    respond_to do |format|
      if @kart.update(kart_params)
        format.html { redirect_to kart_url(@kart), notice: "Kart was successfully updated." }
        format.json { render :show, status: :ok, location: @kart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /karts/1 or /karts/1.json
  def destroy
    @kart.destroy!

    respond_to do |format|
      format.html { redirect_to karts_url, notice: "Kart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kart
      @kart = Kart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kart_params
      params.require(:kart).permit(:size, :color, :speed, :maneuverability, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/karts_helper.rb
module KartsHelper
end

app/views/karts/_form.html.erb
<%= form_with(model: kart) do |form| %>
  <% if kart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kart.errors.count, "error") %> prohibited this kart from being saved:</h2>

      <ul>
        <% kart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Nom, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.label :Couleur, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :Vitesse, style: "display: block" %>
    <%= form.text_field :speed %>
  </div>

  <div>
    <%= form.label :Maniabilité, style: "display: block" %>
    <%= form.text_field :maneuverability %>
  </div>

  <div>
    <%= form.label :Description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :Image, style: "display: block" %>
    <%= form.text_area :image %>
  </div>

  <div class="show_back">
    <%= form.submit %>
  </div>
<% end %>

app/views/karts/_kart.html.erb
<div id="<%= dom_id kart %>" class="show_shpoink">
  <p>
  <img src="<%= kart.image %>" class="kart_image">
  </p>
  <div>
    <p>
    <strong>Nom du Kart:</strong>
    <%= kart.size %>
    </p>
    <p>
    <strong>Vitesse:</strong>
    <%= kart.speed %>
    </p>
    <p>
    <strong>Maniabilité:</strong>
    <%= kart.maneuverability %>
    </p>
    <p>
    <strong>Couleur:</strong>
    <%= kart.color %>
    </p>
    <p>
    <strong>Description:</strong>
    <%= kart.description %>
    </p>
  </div>
  
</div>

app/views/karts/edit.html.erb
<h1>Editing kart</h1>

<%= render "form", kart: @kart %>

<br>

<div>
  <%= link_to "Show this kart", @kart %> |
  <%= link_to "Back to karts", karts_path %>
</div>

app/views/karts/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="phrase_accroche">
<h2>Vous avez encore des doutes sur le choix de votre véhicule sur Mario Kart ? Aucun problème ! Mkmania est la réponse à tout vos problèmes existentiels.</h2>
</div>

<p class="liens_ruby"><%= link_to "Nouveau kart", new_kart_path %></p>

<div id="karts">
 <% @karts.each do |kart| %>
  <div class="voiture">
    <p>
    <img src="<%= kart.image %>" class="kart_image">
    </p>
    <p>
    <%= kart.size %>
    </p>
  <p class="liens_ruby"><%= link_to "Voir ce kart", kart %></p>
  </div>
<% end %>
</div>

app/views/karts/new.html.erb
<h1>Nouveau Kart</h1>

<%= render "form", kart: @kart %>

<br>

<div>
  <%= link_to "Back to karts", karts_path %>
</div>

app/views/karts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kart %>

<div class="show_desc">
  <%= link_to "Edit this kart", edit_kart_path(@kart) %> |
  <%= link_to "Back to karts", karts_path %>

  <%= button_to "Destroy this kart", @kart, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mkmania</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
<header>
<%= image_tag('logo.png') %>
</header>

  <body>
    <%= yield %>
  </body>
    
  <footer>
  <p>©202 - All rights reserved</p>
  <p>Made with : Ruby on Rails, Bootstrap, Midjourney</p>
  <p>DUTEIL Bartholomé, DELGADO Adrian</p>
  </footer>
</html>